version: 2
updates:
  - package-ecosystem: "npm"
    directory: "src/LangChainJSDotNet"
    schedule:
      interval: "daily"
    target-branch: "main"
    allow:
      - dependency-name: "langchain"
