import fs from 'fs/promises';

export const header = `/*
*  This file was autogenerated. Do not commit to source control
*/
import { z } from "zod";
globalThis.z = z;

// *********************
`;

export const footer = `
// *********************`;

export const getItems = async () => {
    let data = await fs.readFile('node_modules/langchain/package.json', 'utf8');
    let pkg = JSON.parse(data);
    return Object.keys(pkg.exports);
};

export const bodyItem = (key) => {
    while (key.startsWith('.') || key.startsWith('/')) {
        key = key.slice(1);
    }
    const id = key.replace(/[\/.]/g, '_') || '_';
    return `
import * as ${id} from 'langchain/${key}';
for (const key in ${id}) {
    globalThis[key] = ${id}[key];
}
`;
};
