export const unsupportedImports = [
    ".", // deprecated
    "./load",
    "./tools/aws_lambda",
    "./tools/webbrowser",
    "./tools/aws_sfn",
    "./agents/toolkits/aws_sfn",
    "./embeddings", // deprecated
    "./embeddings/tensorflow",   
    "./embeddings/hf",
    "./embeddings/googlevertexai",
    "./embeddings/googlepalm",
    "./llms", // deprecated
    "./llms/googlevertexai",
    "./llms/sagemaker_endpoint",
    "./llms/googlepalm",
    "./vectorstores", // deprecated
    "./vectorstores/qdrant",
    "./vectorstores/opensearch",
    "./vectorstores/milvus",
    "./vectorstores/typeorm",
    "./vectorstores/myscale",
    "./vectorstores/redis",
    "./vectorstores/singlestore",
    "./vectorstores/tigris",
    "./vectorstores/analyticdb",
    "./vectorstores/usearch",
    "./text_splitter",
    "./memory",   
    "./memory/zep",
    "./document_loaders", // deprecated
    "./document_loaders/web/apify_dataset",
    "./document_loaders/web/github",
    "./document_loaders/web/s3",
    "./document_loaders/web/confluence",
    "./document_loaders/web/notionapi",
    "./document_loaders/web/sonix_audio",
    "./document_loaders/web/azure_blob_storage_file",
    "./document_loaders/web/azure_blob_storage_container",
    "./document_loaders/web/assemblyai",
    "./chat_models", // deprecated
    "./chat_models/googlevertexai",
    "./chat_models/googlepalm",
    "./chat_models/anthropic",
    "./retrievers", // deprecated
    "./retrievers/zep",
    "./retrievers/hyde",
    "./retrievers/vespa",
    "./retrievers/amazon_kendra",
    "./cache/momento",
    "./cache/redis",
    "./cache/upstash_redis",
    "./cache/ioredis",
    "./stores/doc/gcs",
    "./stores/file/node",
    "./stores/message/dynamodb",
    "./stores/message/momento",
    "./stores/message/redis",
    "./stores/message/upstash_redis",
    "./stores/message/firestore",
    "./stores/message/planetscale",
    "./stores/message/ioredis",
    "./experimental/multimodal_embeddings/googlevertexai",
    "./package.json",
];