name: "Build Branch"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: 'Checkout branch'
        uses: actions/checkout@v3
        
      - name: 'Install npm dependencies'
        run: npm install
        working-directory: src/LangChainJSDotNet

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: 'Start testing API'
        uses: JarvusInnovations/background-action@v1       
        with:
          run: |
            sudo echo "127.0.0.1 api.openai.com" | sudo tee -a /etc/hosts
            npm install -g @mockoon/cli
            sudo mockoon-cli start --port 443 --data ./src/LangChainJSDotNet.IntegrationTests/mockoon-api.json &
          wait-on: |
            tcp:localhost:443
          wait-for: 1m

      - name: 'Run Tests'
        run: dotnet test --runtime linux-x64