name: "Bump Version [Dependabot PR]"

on:
  workflow_run:
    workflows:
      - "Build Branch"
    types:
      - completed

jobs:
  bump-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'dependabot/')
    steps:
      - name: 'Checkout branch'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 'Compute version'
        uses: actions-ecosystem/action-regex-match@main
        id: regex-match
        with:
          text: ${{ github.event.workflow_run.display_title }}
          regex: 'to (\d+\.\d+\.\d+)'

      - name: 'Update version'
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.3
        with:
          file: "src/LangChainJSDotNet/LangChainJSDotNet.csproj"
          version: "${{ steps.regex-match.outputs.group1 }}.0"

      - name: 'Commit and push'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Bump LangChainJSDotNet from ${{ steps.update.outputs.oldVersion }} to ${{ steps.update.outputs.newVersion }}"
          git push origin HEAD:${{ github.event.workflow_run.head_branch }}
